# -*- coding: utf-8 -*-
"""lista Givago

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A0VTwIAu8Y5k2A4Ei7LFIRcFBPeTSFd0
"""

print("SOMA")
a = float(input("Escreva um número: "))
b = float(input("Escreva um número: "))

soma = a + b


print("Soma: ", soma)

print("SUBTRAÇÃO")
a = float(input("Escreva um número: "))
b = float(input("Escreva um número: "))

sub = a - b

print("Subtração", sub)

print("DIVISÃO")
a = float(input("Escreva um número: "))
b = float(input("Escreva um número: "))

div = a / b

print("Divisão: ", div)

print("DOBRO E TRIPLO")
n = float(input("Escreva um número: "))

dob = n * 2
tri = n * 3

print("Dobro: ", dob)
print("Triplo: ", tri)

print("ÁREA DO TRIANGULO")

b = float(input("Digite a b do triangulo: "))
h = float(input("Digite a h do triangulo: "))
area = (b*h) /2

print("Área: ", area)

print("ANTECESSOR E SUCESSOR")
n = float(input("Escreva um número: "))

ant = n - 1
suc = n + 1

print("Antecessor: ", ant)
print("Sucessor: ", suc)

print("PERÍMETRO DO RETÂNGULO")

b = float(input("Digite a b do triangulo: "))
h = float(input("Digite a h do triangulo: "))

p = 2*(b+h)

print("Perímetro: ", p)

print("positivo, negativo 0")
n = float(input("Escreva um número: "))

if n > 0:
    print("Positivo")
elif n < 0:
    print("Negativo")
else:
    print("0")

print("par ou ímpar")
n = float(input("Escreva um número: "))

if n % 2 == 0:
    print("Par")
else:
    print("Ímpar")

print("maior")
a = float(input("Escreva um número: "))
b = float(input("Escreva um número: "))
c= float(input("Escreva um número: "))
if a > b and a > c:
    print("Maior: ", a)
if b > a and b > c:
    print("Maior: ", b)
elif c > a and c > b:
    print("Maior: ", c)

